spring:
  application:
    name: zuul-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:2111/eureka/  # 服务注册
server:
  port: 1117

zuul:
  routes:
    api-user:
      path: /api-user/**
      serviceId: microservice-user
    api-order:
      path: /api-order/**
      serviceId: microservice-order





