# 节点1版本配置
spring:
  application:
    name: microservice-user  # microservice-user的name，唯一标识
server:
  port: 1112
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/  # 服务注册地址